title: ML/CV/NLP/MedicalImaging/Neuroscience Conference Deadlines # (Maintained by @ngohgia, original by @abhshkdz)
description: Countdowns to top Machine Learning/Computer Vision/Natural Language Processing/Medical Imaging/Neuroscience conference deadlines
author: Gia Ngo (original by Abhishek Das)

domain: "ngohgia.github.io/ai-neuro-countdown"
baseurl: ""

github_username: ngohgia
github_repo: ai-neuro-conference-countdown

markdown: kramdown

include: ['_pages']
